### ISSUE TITLE
Django 3 support

### ISSUE THREAD

**Issue by Niklas9** [Niklas9/django-unixdatetimefield#10]
https://docs.djangoproject.com/en/3.0/releases/3.0/

**Comment by bducraux** [comment]
I am getting this error after update Django 2.2 to 3.0

```
 from unixtimestampfield.fields import UnixTimeStampField
  File "C:\Projects\.virtualenvs\project1-xsLDn82m\lib\site-packages\unixtimestampfield\__init__.py", line 1, in <module>
    from .fields import UnixTimeStampField
  File "C:\Projects\.virtualenvs\project1-xsLDn82m\lib\site-packages\unixtimestampfield\fields.py", line 65, in <module>
    from django.utils import six
ImportError: cannot import name 'six' from 'django.utils' (C:\Projects\.virtualenvs\project1-xsLDn82m\lib\site-packages\django\utils\__init__.py)
```

Please evaluate the migration to [six](https://pypi.org/project/six/) as suggested in the [removed-private-python-2-compatibility-apis](https://docs.djangoproject.com/en/dev/releases/3.0/#removed-private-python-2-compatibility-apis) section of the release note.

Thanks for this amazing library!

**Comment by Niklas9** [comment]
Thanks for reporting this Bruno, I’m working on Django 3 support and aim to
have it out later this week, see projects for details (will include full
timezone support as well).

Niklas

**Comment by Niklas9** [comment]
1.1.0 just released with Django 3 support 🎉 

@bducraux I noticed while going through your logs that you're actually using another package -- `unixtimestampfield`, quite similar to this name `unixdatetimefield` and of course in terms of what it does. It doesn't seem to be updated anymore though (last release more than 4 years ago).
You're of course welcome to "upgrade" to `unixdatetimefield` instead :)
